core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index , name='index' ),
    path('orders/', views.orders , name='orders' ),
    path('signup/', views.signup , name='signup' ),
    path('logout/', views.logout_view , name='logout' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html' , authentication_form=LoginForm), name='login')
] 

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index , name='index' )
    
] 

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('<int:pk>', views.detail , name='detail' ),
    path('new/', views.new , name='new' ),
    path('<int:pk>/delete/', views.delete , name='delete' ),
    path('<int:pk>/edit/', views.edit , name='edit' ),
] 

puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Catagory(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Catagories'
        ordering = ('name' ,)

    def __str__(self):
        return self.name
    
class Item(models.Model):
    catagory = models.ForeignKey(Catagory, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    quantity = models.IntegerField(default=1)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password1')

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('catagory' ,'quantity' ,'name' , 'description' , 'price', 'image')
    
        widgets = {
            'catagory' : forms.Select(attrs={
                'class' : INPUT_CLASSES
            }), 
            'name' : forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'quantity' : forms.NumberInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class' : INPUT_CLASSES
            }),
            'price' : forms.NumberInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class' : INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name' ,'quantity',  'description' , 'price', 'image', 'is_sold')
    
        widgets = { 
            'name' : forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'quantity' : forms.NumberInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class' : INPUT_CLASSES
            }),
            'price' : forms.NumberInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class' : INPUT_CLASSES
            })
        }

core/views.py
from django.shortcuts import render, redirect
from item.models import Catagory, Item
from .forms import SignUpForm
from django.contrib.auth import logout
from django.http import HttpResponse
# Create your views here.
def index(request):    
    items = Item.objects.filter(is_sold = False)[0:6]
    catagories = Catagory.objects.all()
    context = {'catagories' : catagories , 'items' : items}
    return render(request, 'core/index.html', context)

def orders(request):
    return render(request, 'core/orders.html')

def signup(request):
    if request.method  == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
        else: 
            form = SignUpForm()
            context = {'form' : form}
            return render(request, 'core/signup.html' , context)
        
def logout_view(request):
    logout(request)
    return redirect('/login/')

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from item.models import Item
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def index(request):
    items = Item.objects.filter(created_by = request.user)
    context = {'items' : items}
    return render(request,'dashboard/index.html' , context)

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    context = {'item' : item}
    return render(request, 'item/detail.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail' , pk=item.id)
    else: 
        form = NewItemForm()
    context = {'form' : form , 'title' : 'Add Item'}
    return render(request,'item/form.html', context)

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail' , pk=item.id)
    else: 
        form = EditItemForm(instance=item)
    context = {'form' : form , 'title' : 'Edit Item'}
    return render(request,'item/form.html', context)


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()

    return redirect('dashboard:index')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %} | Puddle</title>
    <script src="http://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <nav class="py-6 px-6 flex jusrify-between items-center border-b border-gray-200">
        <a href="{% url 'core:index' %}" class="text-xl font-semibold">Puddle</a>
        <div class=" px-3">
          {% if request.user.is_authenticated %}
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500 px-5">New Item</a>
            <a href="{% url 'dashboard:index' %}" class="text-lg font-semibold hover:text-gray-500 px-5">DashBoard</a>
            <a href="{% url 'core:logout' %}" class="text-lg font-semibold hover:text-gray-500 px-5">Logout</a>
              
            {% else %}
            <a href="{% url 'core:signup' %}" class="text-lg font-semibold hover:text-gray-500 px-5">sign up</a>
            <a href="{% url 'core:login' %}" class="text-lg font-semibold hover:text-gray-500 px-5">Login</a>

            {% endif %}
            
             
            <a href="#" class="text-lg font-semibold hover:text-gray-500 px-5">About</a>
            <a href="{% url 'core:orders' %}" class="text-lg font-semibold hover:text-gray-500 px-5">Orders</a>
            <!-- <a href="#" class="text-lg font-semibold hover:text-gray-500 px-5">Privecy Policy</a> -->
            <!-- <a href="#" class="text-lg font-semibold hover:text-gray-500 px-5">Terms of Use</a> -->
            
        </div>
    </nav>
    <div class="px-6 py-6">{% block content %} {% endblock %}</div>
  </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %} 
{% block title %} 
Contact
{% endblock %} 
{% block content %}
<h1>The contact Page</h1>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %} 
{% block title %} 
Welcome
{% endblock %} 
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">
        Newest Items
    </h2>
    <div class="grid grid-col-3 gap-3">
        {% for item in items %}
            <div>
                
                <a href="{% url 'item:detail' item.id %}">
                    <img src="{{item.image.url}}" alt="" >
                </a>
                <div class="p-6 bg-white">
                    <h2 class="text-2xl">
                        {{item.name}}
                    </h2>
                    <p>Price: {{item.price}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>  
<div class="mt-6 px-6 py-12 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">
        Catagories
    </h2>
    <div class="grid grid-col-3 gap-3">
        {% for catagory in catagories %}
            <div>
                
                <div class="p-6 bg-white">
                    <h2 class="text-2xl">
                        {{catagory.name}}
                    </h2>
                    <p>Count: {{catagory.items.count}} items </p>
                </div>
            </div>  
        {% endfor %}
    </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
    Log In
{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">
            Log in
        </h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            {% if form.errors or form.non_field_errors %}
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white" type="submit" >
                Log in
            </button>
        </form>
    </div>
{% endblock %}

core/templates/core/orders.html
{% extends 'core/base.html' %} 
{% block title %} 
Contact
{% endblock %} 
{% block content %}
<h1>Your Orders</h1>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">
            Sign Up
        </h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            {% if form.errors or form.non_field_errors %}
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white" type="submit">
                Sign Up
            </button>
        </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %} 
{% block title %} 
DashBoard
{% endblock %} 
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">
        My Items
    </h2>
    <div class="grid grid-col-3 gap-3">
        {% for item in items %}
            <div>
                
                <a href="{% url 'item:detail' item.id %}">
                    <img src="{{item.image.url}}" alt="" >
                </a>
                <div class="p-6 bg-white">
                    <h2 class="text-2xl">
                        {{item.name}}
                    </h2>
                    <p>Price: {{item.price}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>  
<!-- <div class="mt-6 px-6 py-12 bg-gray-100">
    <h2 class="mb-12 text-2xl text-center">
        Catagories
    </h2>
    <div class="grid grid-col-3 gap-3">
        {% for catagory in catagories %}
            <div>
                
                <div class="p-6 bg-white">
                    <h2 class="text-2xl">
                        {{catagory.name}}
                    </h2>
                    <p>Count: {{catagory.items.count}} items </p>
                </div>
            </div>  
        {% endfor %}
    </div>
</div> -->
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}
{% block title %}
    {{item.title}}
{% endblock %}
{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" alt="item">
        </div>
        <div class="col-span-2 p-6 bg-gray-100">
            <h1 class="mb-6 text-3xl">{{item.name}}</h1>
            <h1 class="mb-6 text-3xl">Price: {{item.price}}</h1>
            <h1 class="mb-6 text-3xl">sold by: {{item.created_by}}</h1>
            <h1 class="mb-6 text-3xl">Catagory: {{item.catagory}}</h1>
            <h1 class="mb-6 text-3xl">Quantity: {{item.quantity}}</h1>
            {% if item.description %}
            <h1 class="mb-6 text-3xl">{{item.description}}</h1>
            {% endif %}
            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white">
                    <p>This is your Item</p>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white">Delete</a>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white">Edit</a>
                </div>                
            {% endif %}
            <a class="block w-full text-lg text-slate-500 hover:file:bg-violet-100 mx-6 px-6" href="{% url 'core:index' %}">Go Back</a>
        </div>
    </div>

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %}
    {{title}}
{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">
        {{title}}
    </h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="spcae-y-4">
            {{form.as_p}}
        </div>
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 text-white" type="submit">Add</button>
    </form>
{% endblock %}